# Generated by Django 5.0.2 on 2025-03-01 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('calculator', 'Calculator'), ('markers', 'Markers'), ('phone_charger', 'Phone Charger')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='rooms.library')),
            ],
        ),
    ]
