# Generated by Django 5.0.2 on 2025-03-08 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["floor__library", "floor__number", "room_number"]},
        ),
        migrations.AddField(
            model_name="library",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for the library used in room IDs (e.g., 'STROZ', 'DIRAC')",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_number",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Room number as displayed on the door (e.g., '101', 'A5')",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.CharField(
                help_text="Unique room identifier (auto-generated, e.g., 'STROZ-F1-101')",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("floor", "room_number")},
        ),
    ]
