# Generated by Django 5.0.2 on 2025-03-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_id_system_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__library', 'floor__number', 'room_number']},
        ),
        migrations.AddField(
            model_name='room',
            name='is_graduate_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(help_text="Unique room identifier (auto-generated, e.g., 'STROZ-F1-101')", max_length=30, unique=True),
        ),
    ]
