# Generated by Django 5.0.2 on 2025-03-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_auto_20250318_0148"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingReservation",
            fields=[],
            options={
                "verbose_name": "Pending Reservation",
                "verbose_name_plural": "Pending Reservations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("rooms.reservation",),
        ),
        migrations.AddField(
            model_name="room",
            name="requires_admin_approval",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, reservations for room require administrator approval prior to confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_graduate_only",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, reservations for room may only be placed by Graduate students",
            ),
        ),
    ]
