# Generated by Django 5.0.2 on 2025-03-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rooms_permissions_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rooms.library')),
            ],
        ),
    ]
